name: Machines
description: A project for the Devathon contest
version: 1.0.0
author: xXAndrew28Xx

main: me.andrew28.machines.Machines

commands:
  machines:
    description: Command for the plugin Machines by xXAndrew28Xx
    aliases: [machine]
    usage: /machines help